test "replace effect":
	set {_inv} to chest inventory with 3 rows
	set slot 2 of {_inv} to 54 dirt
	set slot 3 of {_inv} to 30 bone
	set slot 5 of {_inv} to (45 dirt) named "test"
	set slot 6 of {_inv} to 20 iron ingot
	replace all dirt in {_inv} with bone
	loop all items in inventory {_inv}:
		assert loop-item is not dirt with "replace was incomplete"
	set {_inv2} to {_inv}
	replace all emerald in {_inv} with diamond
	assert {_inv} is {_inv2} with "replacing non-existent item changed inventory"
	assert slot 2 of {_inv} is 54 bone with "slot 2 failed"
	assert slot 3 of {_inv} is 30 bone with "slot 3 failed"
	assert slot 5 of {_inv} is 45 bone with "slot 5 failed"
	assert slot 6 of {_inv} is 20 iron ingot with "slot 6 failed"
