test "altern numbers expression":
	set {_test::*} to integers between 1 and 5
	assert {_test::*} contains 2 with "integer part of numbers failure"
	
	set {_test2::*} to numbers between 1 and 5.1
	assert {_test2::*} doesn't contain 5.1 with "numbers part of numbers failure, end included"
	
	set {_test3::*} to numbers between 1.1 and 4.7
	assert {_test3::*} contains 2.7 with "numbers part of numbers failure, start precision excluded"