test "entity data fixes":
	spawn a baby zombie at spawn of world "world"
	assert last spawned entity is a baby zombie with "last spawned entity should have been a baby zombie"
	assert last spawned entity is a baby entity with "last spawned entity should have been a baby entity"

	spawn an adult zombie at spawn of world "world"
	assert last spawned entity is an adult zombie with "last spawned entity should have been an adult zombie"
	assert last spawned entity is an adult entity with "last spawned entity should have been an adult entity"

	spawn a baby cow at spawn of world "world"
	assert last spawned entity is a baby cow with "last spawned entity should have been a baby cow"
	assert last spawned entity is a baby entity with "last spawned entity should have been a baby entity"

	spawn an adult cow at spawn of world "world"
	assert last spawned entity is an adult cow with "last spawned entity should have been an adult cow"
	assert last spawned entity is an adult entity with "last spawned entity should have been an adult entity"

	spawn a baby sheep at spawn of world "world"
	assert last spawned entity is a baby sheep with "last spawned entity should have been a baby sheep"
	assert last spawned entity is a baby entity with "last spawned entity should have been a baby entity"

	spawn an adult sheep at spawn of world "world"
	assert last spawned entity is an adult sheep with "last spawned entity should have been an adult sheep"
	assert last spawned entity is an adult entity with "last spawned entity should have been an adult entity"
