test "arrows stuck":
	spawn zombie at location(0, 64, 0, world "world")
	set {_m} to last spawned zombie
	assert arrows stuck in {_m} is 0 with "entity spawned with arrows stuck"
	set arrows stuck in {_m} to 31
	assert arrows stuck in {_m} is 31 with "arrows stuck set failed"
	add 5 to arrows stuck in {_m}
	assert arrows stuck in {_m} is 36 with "arrows stuck add failed"
	delete arrows stuck in {_m}
	assert arrows stuck in {_m} is 0 with "arrows stuck delete failed"
