test "arabic numeral":
	assert arabic numeral of "XVI" is 16 with "XVI isn't the roman numeral of 16"
	assert arabic numeral of "IXV" is not set with "IXV is a valid roman numeral"
	assert arabic numeral of "IM" is not set with "IM is a valid roman numeral"
	assert arabic numeal of "105MX" is not set with "105MX is a valid roman numeral"

test "roman numeral":
	assert roman numeral of 16 is "XVI" with "16 isn't the arabic numeral of XVI"
	assert roman numeral of 947 is "CMXLVII" with "CMXLVII isn't the roman numeral of 947"
	assert roman numeral of 49999 is not set with "49999 is low enough to be converted to a roman numeral"
	loop 100 times:
		set {_n} to random integer from 1 to 3333
	assert (arabic numeral of (roman numeral of {_n})) is {_n} with "%{_n}% didn't correctly convert to roman and then numeral (Roman: %roman numeral of {_n}%) %{_n}%"