test "while section":

	set {_x} to 0
	while {_x} < 5:
		add 1 to {_x}
	assert {_x} is 5 with "while loop did not run 5 times (ran %{_x}% times)"

	set {_x} to 0
	do while {_x} < 5:
		add 1 to {_x}
	assert {_x} is 5 with "do while loop did not run 5 times (ran %{_x}% times)"

	set {_x} to 0
	while {_x} > 1:
		add 1 to {_x}
	assert {_x} is 0 with "while loop did not run 0 times (ran %{_x}% times)"

	set {_x} to 0
	do while {_x} > 1:
		add 1 to {_x}
	assert {_x} is 1 with "do while loop did not run 1 time (ran %{_x}% times)"
